antora:
  extensions:
    - '@springio/antora-extensions/partial-build-extension'
    # atlas-extension must be before latest-version-extension so latest versions are applied to imported versions
    - '@antora/atlas-extension'
    - require: '@springio/antora-extensions/latest-version-extension'
    - require: '@springio/antora-extensions/inject-collector-cache-config-extension'
    - '@antora/collector-extension'
    - require: '@springio/antora-extensions/root-component-extension'
      root_component_name: 'security'
site:
  title: Spring Security
  url: http://192.168.1.10:9000/spring-security/reference
  robots: allow
git:
  ensure_git_suffix: false
content:
  sources:
  - url: https://github.com/pderop/spring-security
    branches: [main]
    tags: ['6.+({0..9}).+({0..9})?(-{RC,M}*)']
    start_path: docs
asciidoc:
  attributes:
    page-stackoverflow-url: https://stackoverflow.com/tags/spring-security
    page-related-doc-categories: security
    page-related-doc-projects: framework,graphql
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
  extensions:
  - '@asciidoctor/tabs'
  - '@springio/asciidoctor-extensions'
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.16/ui-bundle.zip
    snapshot: true
runtime:
  log:
    failure_level: warn
